### ISSUE TITLE
Make packages.broadcom.com usable with IPv6

### ISSUE THREAD

**Issue by ldidry** [saltstack/salt-install-guide#10]
Hello,

I don’t know if it’s the right place to talk about that, if not, I’m sorry.

While `repo.saltproject.io` was reachable through IPv6, `packages.broadcom.com` is not, and it’s a problem for IPv6-only servers (some of mine are IPv6-only).

Please, could you make `packages.broadcom.com` reachable through IPv6?

Thank you.

**Comment by ScriptAutomate** [comment]
Duplicate of https://github.com/saltstack/salt-bootstrap/issues/2031
