### ISSUE TITLE
Please update DEB installation instructions to use `deb822` sources.list format

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt-install-guide#4]
Should work as of Debian 9 (Stretch) (or whichever distribution version ships apt >= 1.1). Debian 13 (Trixie) will default to this format and Ubuntu 24.04 already does.

See `man sources.list` for details.

**Comment by ScriptAutomate** [comment]
@dhs-rec Thanks for raising this! I'll be testing it out today on our support deb-based operating systems and will have it included as part of the overhaul if all goes well:
- #2
