### ISSUE TITLE
Provide directions for air-gapped environments / repository syncing with the new packages.broadcom.com repos

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt-install-guide#8]
Page to update:

- https://docs.saltproject.io/salt/install-guide/en/latest/topics/other-install-types/air-gap-install.html

Previously, Salt Project provided directions for tools like `rsync` and `aws` cli for pulling down Salt repositories for use within local/private infra. With the new repository locations, new guidance can be given.

Repository locations:

- Artifactory view
  - [Salt Project RPM Repo](https://packages.broadcom.com/ui/repos/tree/General/saltproject-rpm)
  - [Salt Project DEB Repo](https://packages.broadcom.com/ui/repos/tree/General/saltproject-deb)
  - [Salt Project Generic Repo (Windows, MacOS, etc.)](https://packages.broadcom.com/ui/repos/tree/General/saltproject-generic)
- General repository navigation
  - [Salt Project RPM Repo](https://packages.broadcom.com/artifactory/saltproject-rpm)
  - [Salt Project DEB Repo](https://packages.broadcom.com/artifactory/saltproject-deb)
  - [Salt Project Generic Repo (Windows, MacOS, etc.)](https://packages.broadcom.com/artifactory/saltproject-generic)

**Comment by max-arnold** [comment]
Something like this should work:

```bash
RCLONE_WEBDAV_URL=https://packages.broadcom.com/artifactory/ RCLONE_WEBDAV_VENDOR=other rclone sync :webdav:saltproject-generic/ ./saltproject-generic/
```

**Comment by ScriptAutomate** [comment]
@max-arnold  `wget` could be a simple option too:

```
wget --mirror -nH --cut-dirs=1 https://packages.broadcom.com/artifactory/saltproject-rpm/
wget --mirror -nH --cut-dirs=1 https://packages.broadcom.com/artifactory/saltproject-deb/
wget --mirror -nH --cut-dirs=1 https://packages.broadcom.com/artifactory/saltproject-generic/
```
